require 'open-uri'
require 'nokogiri'
require "bundler/setup"
require_relative "./newegg_scraper_chsbr/version.rb"
require_relative './newegg_scraper_chsbr/data_grabber.rb'
require_relative './newegg_scraper_chsbr/scraper.rb'
require_relative './newegg_scraper_chsbr/user.rb'
require_relative './newegg_scraper_chsbr/name.rb'
require_relative './newegg_scraper_chsbr/price.rb'
require_relative './newegg_scraper_chsbr/cli.rb'
require_relative './newegg_scraper_chsbr/cpu.rb'
require_relative './newegg_scraper_chsbr/descriptors.rb'
require_relative './newegg_scraper_chsbr/shipping.rb'